import { expect, test } from '@playwright/test'

const day5 = 'Day5-奎屯-赛里木湖'
const day8 = 'Day8-尼勒克-乌鲁木齐'
const chapter = (slug) => `/#/chapter/${encodeURIComponent(slug)}`
const settle = (page) => page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))))

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'light' })
})

test('day controls respect boundaries and restore a visible tab without scrolling the page', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: '打开每日速查', exact: true }).click()
  await expect(page.getByRole('button', { name: '查看上一天' })).toBeDisabled()
  await page.getByRole('button', { name: '查看下一天' }).click()
  await expect(page.locator('#daily-field-tab-D1')).toHaveAttribute('aria-selected', 'true')
  await page.locator('#daily-field-tab-D1').focus()
  await page.keyboard.press('End')
  await expect(page.locator('#daily-field-tab-D9')).toBeFocused()
  await expect(page.getByRole('button', { name: '查看下一天' })).toBeDisabled()
  await page.reload()
  await expect(page.locator('#daily-field-tab-D9')).toHaveAttribute('aria-selected', 'true')
  await settle(page)
  const restored = await page.locator('#daily-field-tab-D9').evaluate((tab) => {
    const target = tab.getBoundingClientRect()
    const track = tab.parentElement.getBoundingClientRect()
    return { left: target.left - track.left, right: target.right - track.right, scrollY }
  })
  expect(restored.left).toBeGreaterThanOrEqual(0)
  expect(restored.right).toBeLessThanOrEqual(1)
  expect(restored.scrollY).toBeLessThan(10)
  await page.getByRole('navigation', { name: '移动端快捷导航' }).getByRole('button', { name: '每日速查', exact: true }).click()
  await page.getByRole('button', { name: '查看上一天' }).click()
  await expect(page.locator('#daily-field-tab-D8')).toHaveAttribute('aria-selected', 'true')
})

test('section navigation tracks clicks and manual scrolling without changing the route', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const url = page.url()
  const nav = page.getByRole('navigation', { name: '本页章节' })
  for (const [name, id] of [['每日速查', 'dailyGuide'], ['预算试算', 'tripBudget'], ['出行准备', 'intelligence']]) {
    const button = nav.getByRole('button', { name: new RegExp(name) })
    await button.click()
    await expect(button).toHaveAttribute('aria-current', 'true')
    await settle(page)
    const top = await page.locator(`#${id}`).evaluate((element) => element.getBoundingClientRect().top)
    expect(top).toBeGreaterThanOrEqual(116)
    expect(top).toBeLessThan(200)
    const within = await button.evaluate((el) => {
      const bounds = el.parentElement.getBoundingClientRect()
      const rect = el.getBoundingClientRect()
      return rect.left >= bounds.left - 1 && rect.right <= bounds.right + 1
    })
    expect(within).toBe(true)
    expect(page.url()).toBe(url)
  }
  await page.locator('#foodJourney').evaluate((el) => scrollTo({ top: el.getBoundingClientRect().top + scrollY - 140, behavior: 'instant' }))
  await expect(nav.getByRole('button', { name: /沿途美食/ })).toHaveAttribute('aria-current', 'true')
})

test('reading size persists and chapter rails leave the reader at the top', async ({ page }) => {
  await page.goto(chapter(day8))
  await expect(page.locator('.chapter-content')).toBeVisible()
  await settle(page)
  expect(await page.evaluate(() => scrollY)).toBeLessThan(10)
  const size = page.getByRole('button', { name: '大字阅读', exact: true })
  await expect(page.locator('.markdown-body')).toHaveCSS('font-size', '16px')
  await size.click()
  await expect(size).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.markdown-body')).toHaveCSS('font-size', '18px')
  await page.reload()
  await expect(size).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.markdown-body')).toHaveCSS('font-size', '18px')
  await page.locator('.reader-focus__item').first().click()
  await settle(page)
  const focused = await page.evaluate(() => {
    const toolbar = document.querySelector('.reader-toolbar').getBoundingClientRect()
    const heading = document.activeElement.getBoundingClientRect()
    return { target: heading.top, toolbar: toolbar.bottom, overflow: document.documentElement.scrollWidth - innerWidth }
  })
  expect(focused.target).toBeGreaterThanOrEqual(focused.toolbar)
  expect(focused.overflow).toBeLessThanOrEqual(1)
  await size.click()
  await expect(page.locator('.markdown-body')).toHaveCSS('font-size', '16px')
})

test('mobile daily shortcut opens the guide for the chapter being read', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(chapter(day5))
  await expect(page.locator('.chapter-content')).toBeVisible()
  await page.getByRole('navigation', { name: '移动端快捷导航' }).getByRole('button', { name: '每日速查' }).click()
  await expect(page.locator('#daily-field-tab-D5')).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('#daily-field-panel-D5')).toBeVisible()
  await expect(page.getByRole('navigation', { name: '本页章节' }).getByRole('button', { name: /每日速查/ })).toHaveAttribute('aria-current', 'true')
})

test('search suggestions work by keyboard and text navigation keeps native editing behavior', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: '打开搜索', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '搜索 RoadBook' })
  const suggestion = dialog.getByRole('button', { name: '赛里木湖', exact: true })
  await suggestion.focus()
  await page.keyboard.press('Enter')
  const input = dialog.getByRole('combobox')
  await expect(input).toHaveValue('赛里木湖')
  await expect(input).toBeFocused()
  await expect(dialog.getByRole('option').first()).toBeVisible()
  await page.keyboard.press('Home')
  expect(await input.evaluate((el) => el.selectionStart)).toBe(0)
  await page.keyboard.press('End')
  expect(await input.evaluate((el) => el.selectionStart)).toBe(4)
  await dialog.getByRole('button', { name: '清空搜索' }).click()
  await expect(input).toHaveValue('')
  await expect(input).toBeFocused()
  await input.fill('找不到的路书章节xyz')
  await expect(dialog.locator('.search-palette__empty')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
})

test('system dark mode covers search and printing while an explicit theme choice takes precedence', async ({ page, isMobile }) => {
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: '打开搜索', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '搜索 RoadBook' })
  await expect(dialog).toBeVisible()
  const overlayBackground = await dialog.evaluate((el) => getComputedStyle(el).backgroundColor)
  expect(overlayBackground).not.toBe('rgb(255, 255, 255)')
  await page.keyboard.press('Escape')
  await page.goto(chapter(day5))
  await expect(page.locator('.chapter-content')).toBeVisible()
  const darkBackground = await page.locator('body').evaluate((el) => getComputedStyle(el).backgroundColor)
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.reader-toolbar')).toBeHidden()
  await expect(page.locator('.day-route-map-body')).toBeVisible()
  await page.emulateMedia({ media: 'screen' })
  await expect(page.locator('body')).toHaveCSS('background-color', darkBackground)
  const theme = isMobile ? page.getByRole('navigation', { name: '移动端快捷导航' }).getByRole('button', { name: '主题' }) : page.locator('.theme-toggle')
  await theme.click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
})

test('reader maps open on demand, chapter changes reset them, and the index reaches emergency contacts', async ({ page }) => {
  await page.goto(chapter(day5))
  await expect(page.locator('.chapter-content')).toBeVisible()
  const toggle = page.locator('.day-route-map-toggle')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await expect(page.locator('.day-route-map-body')).toBeVisible()
  await page.goto(chapter(day8))
  await expect(page.locator('#readerTitle')).toContainText('Day 8')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await page.goto(chapter('00-总目录'))
  await page.locator('.book-directory a[data-doc="专题-新疆旅行应急宝典.md"]').click()
  await expect(page.locator('#readerTitle')).toHaveText('新疆旅行应急宝典')
  await page.locator('.reader-focus__item').first().click()
  await expect(page.locator('[id="1-联系卡"]')).toBeFocused()
  await expect(page.locator('.emergency-contacts a')).toHaveCount(3)
  for (const number of ['110', '120', '119']) {
    await expect(page.locator(`.emergency-contacts a[href="tel:${number}"]`)).toBeVisible()
  }
})
