<template>
  <div class="chapter-content">
    <h2 id="专题摘要">沿着这条路，读懂五种风景</h2>
    <p class="article-lead">从白哈巴的木屋到唐布拉的山谷，这条路上的风景各有值得停下目光的地方：喀纳斯看河湾的曲线，赛里木湖看水色与光线，库尔德宁看森林与草甸。带着这些线索到现场，把每一站看得更细。出发、接驳与返程时刻，按对应日程执行。</p>

    <h2 id="关键结论">五处风景，按路线读</h2>
    <h3 id="2-白哈巴在云端一晚与双日接驳">白哈巴｜木屋、白桦与村落生活</h3>
    <p class="destination-lead">远山之外，也看看一扇院门、一段木篱和木屋边的日常。住进白哈巴的一晚，让赶路的节奏暂时慢下来。</p>
    <figure class="section-media" data-asset="baihaba-autumn"><img data-asset-src="baihaba-autumn" alt="白哈巴景区秋季雪山与金色森林全景" src="@/assets/images/baihaba-autumn.webp" loading="lazy" decoding="async" style="object-position:50% 50%"><figcaption><strong>白哈巴景区 · 秋季山林</strong><span>白哈巴的初雪山脊与金色秋林，季节感贴近十月上旬行程。</span><small>keshb3 · <a href="https://unsplash.com/license" target="_blank" rel="noreferrer">Unsplash License</a> · <button type="button" class="credit-link" data-action="open-credit" data-asset="baihaba-autumn">许可详情</button></small></figcaption></figure>
    <ul><li><strong>怎么走：</strong>留村时在开放主街慢走 45—60 min，再选热茶或一处允许进入的观景点。南村的在云端并不在老村核心，先向民宿确认入口与接送。</li><li><strong>怎么看：</strong>留意木屋材料、院落和林缘的颜色；人物、院门与生活细节拍摄先征得同意。初雪与晨雾是可能遇到的天气，不能作为必看承诺。</li><li><strong>怎么选：</strong>主选 D2 下午观鱼台、D3 三湾后回布尔津；备选 D2 下午留村、D3 三湾和观鱼台同日并续住白哈巴。骑马或音乐体验须实际有合适服务，不能默认民宿已经包含。</li><li><strong>先确认：</strong>边防证须提前申请并获批：符合条件者在支付宝搜索“移民局12367”，旅游前往地选新疆阿勒泰地区；<a href="#/chapter/Day2-%E5%B8%83%E5%B0%94%E6%B4%A5-%E7%99%BD%E5%93%88%E5%B7%B4?section=%E6%94%AF%E4%BB%98%E5%AE%9D%E8%BE%B9%E9%98%B2%E8%AF%81%E5%8A%9E%E7%90%86%E6%B5%81%E7%A8%8B" data-doc="Day2-布尔津-白哈巴.md" data-section="支付宝边防证办理流程">完整操作流程见 D2</a>。网上受理后 3 个工作日内决定是否批准，受理中不能作进村凭证；完整电子证或打印件与有效身份证件备齐。社会车辆准入、村内接驳与保暖条件另核。具体适用身份与材料见 <a href="https://s.nia.gov.cn/mps/bszy/dzbjtxz/blzy/202604/t20260414_1001.html" target="_blank" rel="noreferrer">国家移民管理局指南</a>。</li></ul><p><a href="#/chapter/Day2-%E5%B8%83%E5%B0%94%E6%B4%A5-%E7%99%BD%E5%93%88%E5%B7%B4?section=%E4%BB%8A%E6%97%A5%E5%8F%AF%E9%80%89%E9%A1%B9" data-doc="Day2-布尔津-白哈巴.md" data-section="今日可选项">查看白哈巴的抵达、用餐与两种玩法</a></p>

    <h3 id="3-喀纳斯d3-区间车一日">喀纳斯｜三湾的曲线，湖岸的留白</h3>
    <p class="destination-lead">看三湾，目光沿着河曲走进林地；到湖岸，再停下来看看水色与远山。想从容欣赏这两种尺度的风景，先为往返接驳留足时间。</p>
    <figure class="section-media" data-asset="kanas-autumn-river"><img data-asset-src="kanas-autumn-river" alt="喀纳斯河秋景：秋叶繁茂、河水碧绿，蜿蜒穿过秋季森林" src="@/assets/images/kanas-autumn-river.webp" loading="lazy" decoding="async" style="object-position:50% 50%"><figcaption><strong>喀纳斯河 · 阿勒泰地区</strong><span>喀纳斯河秋景 · 十月河谷层林尽染的现场意象</span><small>WANG Jared · <a href="https://www.pexels.com/license/" target="_blank" rel="noreferrer">Pexels License（免费商用、可修改、无需署名）</a> · <button type="button" class="credit-link" data-action="open-credit" data-asset="kanas-autumn-river">许可详情</button></small></figcaption></figure>
    <ul><li><strong>三湾看什么：</strong>神仙湾看浅滩和林线；月亮湾保留经典河曲与主观景台；卧龙湾看开阔滩林。没有晨雾也可以观察河岸层次，D3 上午也不保证遇见晨雾。</li><li><strong>步行怎么留：</strong>月亮湾—卧龙湾约 2.6 km 只在栈道开放、路面和体力允许时走；人多就改区间车，不占用返程候车余量。</li><li><strong>观鱼台怎么排：</strong>主选在 D2 下午登台，D3 专注三湾；备选 D3 同日游三湾和观鱼台，需留专线往返、排队与 1,068 级台阶时间，建议整体约 2.5—3 小时。</li><li><strong>接驳要分清：</strong>D2 12:30 从民宿出发乘村内 2 号线到游客中心换乘，末班回白哈巴；D3 主选 15:45 抵白哈巴、16:30 前自驾出村，备选末班返白哈巴续住。用户 2026-09-29 补充：白喀双向末班均为 <strong>20:00</strong>，乘末班时 19:30 前候车；村内公交、观鱼台专线及其他班次另核。</li><li><strong>车窗赏景：</strong>面向车辆前进方向，<strong>喀纳斯去白哈巴坐左侧，白哈巴去喀纳斯坐右侧</strong>，白天班次沿途赏景，20:00 末班按夜间返村准备（用户当地补充）。</li></ul><p>景区<a href="https://www.kns.gov.cn/005/005002/20250505/1811ea4d-6459-4205-b8bd-27e2aa5dfb52.html" target="_blank" rel="noreferrer">2025 年夏季公告</a>仅提供历史运营与购票渠道参考，不能证明 2026 国庆的班次、放票或车辆准入。<a href="#/chapter/Day3-%E7%99%BD%E5%93%88%E5%B7%B4-%E5%96%80%E7%BA%B3%E6%96%AF%E5%85%A8%E5%A4%A9?section=%E4%B8%A4%E5%A4%A9%E5%8F%AA%E8%BF%9B%E4%B8%80%E6%AC%A1%E7%9A%84%E9%80%89%E6%8B%A9" data-doc="Day3-白哈巴-喀纳斯全天.md" data-section="两天只进一次的选择">先选 D2 / D3 的组合</a>。</p>

    <h3 id="5-赛里木湖d5-傍晚日落与d6-环湖">赛里木湖｜一个傍晚，一个上午</h3>
    <p class="destination-lead">同一片湖水，会随光线和风换一副面貌。D5 看远景与日落，D6 再沿北岸、西岸观察水色和草甸，让一个傍晚与一个上午各有收获。</p>
    <figure class="section-media" data-asset="sayram-panorama"><img data-asset-src="sayram-panorama" alt="从湖畔山丘俯瞰赛里木湖、远山、低云与针叶树" src="@/assets/images/sayram-panorama.webp" loading="lazy" decoding="async" style="object-position:51% 49%"><figcaption><strong>赛里木湖</strong><span>赛里木湖远景 · 湖面与高原天气层</span><small>BitsRot · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · <button type="button" class="credit-link" data-action="open-credit" data-asset="sayram-panorama">许可详情</button></small></figcaption></figure>
    <ul><li><strong>D5 二选一：</strong>松树头适合看湖泊全景；东岸慢行适合近距离看水、拍合影与休息。16:20 前准备就绪且允许南岸往返才登顶，18:30 前回停车场。</li><li><strong>D6 看不同岸段：</strong>09:00 按开放方向出发，北岸和西岸选 2—3 处合法停车点；12:30 前出湖赴伊宁。D5 未去松树头，也不在 D6 补齐整圈。</li><li><strong>十月期待：</strong>看湖色、远山和草甸的秋季层次；夏季花海、满坡鲜绿和天鹅都不保证。风大或岸线湿滑时缩短步行，别为等蓝天错过出湖时间。</li><li><strong>两天票务：</strong>先核酒店是否在检票区内、出园回店及次日再入园是否覆盖，再核自驾费、实际通行方向与南门开放。新华社 2026-08-03 转述联合工作组通报，8 月 20 日起按核定座位数收费，本次六座 L8 为 ¥180/车。门票、双日有效、酒店边界与再次入园仍看官方购票页，不能只按实际乘坐四人套五座档。</li></ul><p><a href="#/chapter/Day5-%E5%A5%8E%E5%B1%AF-%E8%B5%9B%E9%87%8C%E6%9C%A8%E6%B9%96?section=%E6%B9%96%E8%BE%B9%E6%85%A2%E7%9C%8B%E7%9A%84%E6%9B%BF%E6%8D%A2%E6%96%B9%E6%A1%88" data-doc="Day5-奎屯-赛里木湖.md" data-section="湖边慢看的替换方案">D5 傍晚怎么选</a> · <a href="#/chapter/Day6-%E8%B5%9B%E9%87%8C%E6%9C%A8%E6%B9%96-%E4%BC%8A%E5%AE%81?section=%E7%8E%AF%E6%B9%96%E8%B7%AF%E7%BA%BF%E6%9C%8D%E4%BB%8E%E5%BD%93%E6%97%A5%E5%AE%98%E6%96%B9%E5%8D%95%E5%90%91%E7%BB%84%E7%BB%87" data-doc="Day6-赛里木湖-伊宁.md" data-section="环湖路线服从当日官方单向组织">D6 环湖与出湖条件</a></p>

    <p><strong>10月9日施工安排已核：</strong><a href="https://mp.weixin.qq.com/s?__biz=MzkyOTcyMTk4NA==&amp;mid=2247589180&amp;idx=1&amp;sn=13573abc92620933142b62fa753c5686&amp;chksm=c31cfc1e695cb9f4d6e4927bec2978d042354cd50d796560c942176561481e9fe0ef625dcaea&amp;scene=27" target="_blank" rel="noopener noreferrer">伊犁文旅转载景区公告</a>（公告落款2026-08-22、转载08-24）明确东沟全线8月26日起封闭，10月26日仅为计划通车日期，游览改中沟进、中沟出。阿尤赛未被公告单独确认，退出主流程；只有景区允许且能同路安全折返才另考虑，禁止进入东沟施工区。</p><p><strong>进镇先核施工导行：</strong><a href="https://www.xjgl.gov.cn/xjgl/c114161/202608/6d895a8ee07f4218a2d185898e548547.shtml" target="_blank" rel="noopener noreferrer">巩留县交通运输局公告</a>明确X737团结渠桥9月1日—11月30日全封闭，主选按S329 K8+200→X060→接回X737导行。D7 按上述官方绕行，全天用车预算约 300 km / 6 h（保守估算，含绕行机动，非高德完整实测；餐休与景区活动另计）；11:30—12:00到镇只是保守参考，遇延误缩短骑马或近处栈道，16:15喀峰收线不后移。回新源走宝柯路、G578，不走CZ18白沟或牧道。</p>
    <h3 id="库尔德宁d7森林骑马与观景">库尔德宁｜齐梦德森林草甸与中沟往返</h3>
    <p class="destination-lead">这一站的目光落在云杉、草甸与喀峰之间。D7 从伊宁 08:00 出发，经施工导行参考 11:30—12:00 到镇；12:00—12:40 午餐，13:00 从游客中心经中沟入园，把 13:50—16:10 留给马队准备、骑马上山、观景和徒步下山。</p>
    <ul><li><strong>时间安排：</strong>08:00从伊宁亚朵实际驾车，09:30—09:50完整休息；经交通局导行，11:30—12:00参考到镇（施工可延后）。12:00—12:40马家或特色老牌子拌面午餐，12:40—13:00游客中心购票并核双向车流，13:00—13:50经中沟、十里画廊到喀峰营地；13:50—16:10齐梦德骑马上山、徒步下山。16:15从喀峰营地收线，中沟原路返回，17:00—17:20游客中心外休息，17:20赴新源，19:00—19:30到汉庭；19:45—20:45就近晚餐并补油。</li><li><strong>齐梦德：</strong>先核马队营业、人数、护具、四人总价和上山终点，预算约2h20min包含上山、观景与下山；牵马服务与价格按实际确认，不能从高德驾车时间推算骑马。步行下山只在栈道/路面、体力和天气允许时执行。</li><li><strong>阿尤赛：</strong>公告未单独确认开放状态，退出主流程；只有景区允许且可同路安全折返才另考虑。严禁驶入东沟施工区，16:15从喀峰营地按时收线。</li><li><strong>驾车与票务：</strong>D7 全天约 300 km / 6 h，含官方绕行与中沟往返，作为保守用车预算，非高德完整实测；6 h 含绕行机动，餐休、骑马徒步另计。门票、自驾准入、中沟双向组织、停车和马队十月开放由官方与现场确认；若不准自驾，按景交重新核时间，不能沿用内部驾车段。</li></ul>

    <h3 id="6-唐布拉百里画廊d7-独库环线穿越">唐布拉｜D8返程主选，河谷后接独库北段</h3>
    <p class="destination-lead">沿喀什河谷，草甸、林线和牧场依次进入视野。返程途中，在一处合法停车点短暂停留，看清河谷的层次，再接上独库北段。</p>
    <figure class="section-media" data-asset="tangbula-grassland"><img data-asset-src="tangbula-grassland" alt="唐布拉草原阴云下沿牧道行进的羊群" src="@/assets/images/tangbula-grassland.webp" loading="lazy" decoding="async" style="object-position:52% 60%"><figcaption><strong>尼勒克县 · 唐布拉草原</strong><span>唐布拉草原 · 百里画廊所在区域的牧场与转场生活</span><small>lwtt93 · <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noreferrer">CC BY 2.0</a> · <button type="button" class="credit-link" data-action="open-credit" data-asset="tangbula-grassland">许可详情</button></small></figcaption></figure>
    <ul><li><strong>主选：</strong>D8 09:00起床、09:40从新源汉庭驾车，经S316→S315唐布拉百里画廊→乔尔玛→独库北段→奎屯火车站服务点，276.657km / 5:07:33纯驾驶；沿途选择合法停车点短看秋林，不绕入仙女湖等深线。</li><li><strong>那拉提备选：</strong>经那拉提→乔尔玛加入玉希莫勒盖高山路段，314.139km / 6:18:21，比唐布拉多1:10:48。首次休息20min、乔尔玛午餐25min、共同北段休息20min、补油10min共75min，09:40发车静态约17:13到服务点，至17:30仅约17min余量，交车进站更紧。仅在晴稳、全线开放、预约匹配、当日全线纯驾明显缩短且休息/交车/火车衔接均闭环时采用；17:00到点并留30min机动需纯驾≤5h35min。</li><li><strong>封路备选：</strong>共同乔尔玛→独山子段封闭时，两条景观方案都失效，改G577精伊高速→G30连霍高速441.654km / 5:36:56。前140.691km / 2:09:15到苏布台北为普通道路，之后约301km / 3:27:41高速；不能把新源出发全程视为高速。</li><li><strong>返程边界：</strong>目标17:00、延误上限17:30抵达还车点。交车20min、带行李到进站口留10min；17:30才到可能18:00进站，不能保证18:06火车。收官90min正餐已取消。</li><li><strong>道路与季节：</strong>S316仍有山地峡谷，唐布拉不是全天候替代独库的道路。6月19日正式指南明确6月25日起独库北段预约通行，十月规则与开放状态行前核对；往年封路日期不能证明今年开放。秋色与牧群位置随天气变化，不预设蜂场、马队或漂流十月营业。</li></ul><p><a href="https://www.btzx.com.cn/web/2026/6/19/ARTI1781836732151837.html" target="_blank" rel="noreferrer">2026独库北段正式预约指南</a>为已发布规则来源；实际入口和时段以临行官方平台为准。本次住宿为新源汉庭，旧尼勒克与蜜蜂小镇订单仅保留售后处理责任。</p>

    <p><strong>先按含休息的时间判断：</strong>D7 16:15从喀峰营地收线，中沟原路返回游客中心；高德回程约20.2 km / 29 min，实际按45 min留会车。17:00—17:20在游客中心外完整休息，17:20经宝柯路、G578赴新源，纯驾约79.7 km / 1 h 40 min，19:00—19:30到汉庭，19:45—20:45就近晚餐并补油。</p>
    <p><strong>唐布拉主选：</strong>D8 09:40发车，必要停车85 min（画廊20、乔尔玛午餐35、共同北段休息20、补油10），纯驾后基础到点16:12:33，至17:00留47:27道路机动。</p>
    <p><strong>封路备选：</strong>G577/G30方案停车80 min（首次休息20、午餐30、第二次休息20、补油10），基础到点16:36:56，至17:00留23:04道路机动。</p>
    <p><strong>那拉提条件备选：</strong>必要停车75 min后基础约17:13到点，距17:30仅约17 min，交车与18:06火车衔接更紧；当前快照不作为正常可执行方案。只有当日全线纯驾明显缩短、全线开放，且休息、交车与火车衔接均已落实，才可采用；若要17:00到点并留30 min道路机动，全线纯驾须≤5 h 35 min。</p>

    <h2 id="沿途了解">沿途了解</h2>
    <h3 id="1-五彩滩d1-条件日落">五彩滩｜沿途了解，本次不入园</h3>
    
    <figure class="section-media" data-asset="wucaitan"><img data-asset-src="wucaitan" alt="五彩滩彩色侵蚀岩丘、额尔齐斯河与对岸树林" src="@/assets/images/wucaitan.webp" loading="lazy" decoding="async" style="object-position:50% 56%"><figcaption><strong>布尔津县 · 五彩滩</strong><span>五彩滩 · 河流与风化地貌的对照</span><small>Nyx Ning · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noreferrer">CC BY-SA 3.0</a> · <button type="button" class="credit-link" data-action="open-credit" data-asset="wucaitan">许可详情</button></small></figcaption></figure>
    <p>彩色侵蚀岩丘与对岸树林隔河相望，额尔齐斯河从中经过；这组对照，是认识布尔津河谷地貌的一条线索。本次 D1 是火车接驳后的长途日，已取消五彩滩；不在 D2 早晨或返城晚上补入，也不再为它安排购票任务。</p>

    <h3 id="4-d4布尔津至奎屯转场">克拉玛依方向｜车窗里的戈壁与工业地貌</h3>
    
    <figure class="section-media" data-asset="karamay-pumpjacks"><img data-asset-src="karamay-pumpjacks" alt="克拉玛依日落时分岩石地貌前的抽油机群" src="@/assets/images/karamay-pumpjacks.webp" loading="lazy" decoding="async" style="object-position:50% 55%"><figcaption><strong>克拉玛依 · 抽油机群</strong><span>克拉玛依 · 抽油机与岩地日落（D4 克拉玛依中转意象参考图）</span><small>wang jared · <a href="https://www.pexels.com/license/" target="_blank" rel="noreferrer">Pexels License（免费商用、可修改、无需署名）</a> · <button type="button" class="credit-link" data-action="open-credit" data-asset="karamay-pumpjacks">许可详情</button></small></figcaption></figure>
    <p>D4 从布尔津经 G217、G3014 和克拉玛依方向到奎屯，静态约 469.4 km / 5 h 27 min。途中只在既定的合法休息点观察戈壁与工业地貌；午餐、补油与换手优先。铁热克提与哈巴河不在 D4 的补给动线上，不据旧文案绕行。</p>

    <h2 id="操作清单">入园前逐项确认</h2>
    <h3 id="9-月再逐项核一遍">现在补齐资料，游览前再确认</h3>

    <ul><li><label class="task task-live"><input type="checkbox" data-check-index="0"> <span>五彩滩已取消确认不再购票；奎屯站取车约定、奎屯午餐店铺营业状态与 D1 火车票</span></label></li><li><label class="task task-live"><input type="checkbox" data-check-index="1"> <span>白哈巴电子证、社会车辆到村停车准入、在云端订单状态、D2 接行李与两班接驳、D3 条件接驳及退房行李送停车场</span></label></li><li><label class="task task-live"><input type="checkbox" data-check-index="2"> <span>D2 村内 2 号线、观鱼台专线与末班回程；D3 主选能在 15:45 抵白哈巴的回程，备选末班返村与续住</span></label></li><li><label class="task task-live"><input type="checkbox" data-check-index="3"> <span>喀纳斯国庆出入园、D2 观鱼台与 D3 三湾接驳开放；备选 D3 同日游览</span></label></li><li><label class="task task-live"><input type="checkbox" data-check-index="4"> <span>D2 直达白哈巴线路、D3 白哈巴→布尔津、D4 G217/G3014 路况与两晚酒店</span></label></li><li><label class="task task-live"><input type="checkbox" data-check-index="5"> <span>赛里木湖门票·环湖交通组织（方向/开放岸段/南门状态）</span></label></li><li><label class="task task-live"><input type="checkbox" data-check-index="6"> <span>D7库尔德宁自驾/景交准入、中沟双向组织、齐梦德马队和徒步路况、X737施工导行；D8独库共同北段与那拉提备选段开放、预约入口及时段、S316/S315合法停车与补给；G577/G30备选和17:00服务点抵达链</span></label></li></ul>

    <h2 id="动态信息提醒">开放、票务与资料日期</h2>
    <div class="alert-banner is-info"><strong>开放情况以临行公告为准</strong><p>截至 2026-09-30，白哈巴/喀纳斯、赛里木湖、库尔德宁与唐布拉百里画廊的 2026 国庆专项公告均须临行复核（五彩滩已取消，无票务任务）。所有地图里程、时间和营业标记都只是查询时的静态基线，不构成 2026 国庆承诺。以临行官方公告为准。</p></div>
</div>
</template>
